import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import Navbar from '../Navbar'
import styles from './MainLayout.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function MainLayout ({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Navbar />
        { children }
      </main>
    </>
  )
}
